server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
   username: 'nine'
   url: jdbc:postgresql://postgres:5432/customer
   password: 999
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false