server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: nine
    url: jdbc:postgresql://localhost:15432/fraud
    password: 999
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  zipkin:
   base-url: http://localhost:9411